### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by liangkai0088** [a6678696/JavaBookSharing#1]
你好 阿里云的链接失效了

**Comment by a6678696** [comment]
哪个链接?

**Comment by liangkai0088** [comment]
> 

https://www.aliyundrive.com/s/6czs9qrJriN 阿里云的链接都失效了

**Comment by a6678696** [comment]
我点了，没失效
![image](https://user-images.githubusercontent.com/45851356/219853858-ba25bc12-5c79-405e-b9b1-2b5084f91f2c.png)
